"""add row

Revision ID: 4567998af4a5
Revises: 3854dca98b33
Create Date: 2024-03-09 15:55:53.458799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4567998af4a5'
down_revision = '3854dca98b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amazing_race_contestants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amazing_race_contestants', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
