"""set up

Revision ID: d360583c3601
Revises: 
Create Date: 2024-02-26 19:20:47.801420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd360583c3601'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_table('tribes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tribes'))
    )
    op.create_table('amazing_race_contestants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_members', sa.String(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('is_eliminated', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_amazing_race_contestants_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amazing_race_contestants'))
    )
    op.create_table('survivor_contestants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('hometown', sa.String(), nullable=True),
    sa.Column('current_residence', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('is_in_merge', sa.Boolean(), nullable=True),
    sa.Column('is_eliminated', sa.Boolean(), nullable=True),
    sa.Column('is_on_jury', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('tribe_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_survivor_contestants_team_id_teams')),
    sa.ForeignKeyConstraint(['tribe_id'], ['tribes.id'], name=op.f('fk_survivor_contestants_tribe_id_tribes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survivor_contestants'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survivor_contestants')
    op.drop_table('amazing_race_contestants')
    op.drop_table('tribes')
    op.drop_table('teams')
    # ### end Alembic commands ###
